### ISSUE TITLE
Track balance for specific addresses

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/tezos_exporter#4]
Related to ecadlabs/go-tezos#3
This metric will consume the go-tezos get balance method

Tracking balance of a wallet overtime is useful for alerting and visualization. A timeseries of balance is a facsimile, and shouldn't be used for accounting. The value of exposing address specific values comes from using prometheus tooling for tracking and alerting.

The exporter would need to have a config file where the operator can list addresses of interest.

`curl localhost:8732/chains/{chain_id}/blocks/{block_id}/context/delegates/{pkh}/balance`

`chain_id` is a symbolic chain identifier, e.g. main or test, or their equivalent Base58-encoded hash, e. g. NetXzGDuYoAawjv.
`block_id` is a symbolic block identifier, e.g. head of genesis, or any Base58-encoded block hash, e.g.

Concrete example against `mainnet`
`curl localhost:8732/chains/main/blocks/head/context/delegates/tz1Yju7jmmsaUiG9qQLoYv35v5pHgnWoLWbt/balance`

**Comment by juliusv** [comment]
@jevonearth Do you want this functionality only for delegate balances or also for contract balances (`[...]/context/contracts/<contract_id>/balance`)?

**Comment by jevonearth** [comment]
Closing. We will stick to operational node metrics, and avoid on-chain metrics.
