### ISSUE TITLE
Metrics to track mempool

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/tezos_exporter#5]
See: ecadlabs/go-tezos#4 for corresponding client API issue

We want to track mempool metrics.

We have arrays named:
* applied
* refused
* branch_refused
* branch_delayed
* unprocessed

Each one contains a list. Proposed labels are `kind` and `protocol`

**Comment by juliusv** [comment]
@jevonearth Are you thinking of separate metrics for `applied`, `refused`, etc.? I think this might make sense since they don't all have the same label names (`applied` doesn't have a protocol field) and also can be seen as separate-enough metrics.

With `kind` you mean the operation kind, not the error kind, correct? Your example output has both.

**Comment by juliusv** [comment]
@jevonearth Actually, the way the go-tezos code is currently structured, it'd be easier to just put them all into one metric and live with the fact that `protocol` is unset for the `applied` pool. But I'm fine doing it either way.

**Comment by juliusv** [comment]
@jevonearth Another question: should we only report data on one chain? If so, I guess that has to be flag-configured?

**Comment by jevonearth** [comment]
Hi @juliusv pardon the delay, I have been travelling which has prevented me from following up.

Putting them into one metric with a label feels okay to me, as all the data comes back in a single request anyway. 

WRT `kind` I was originally thinking about the `operation` kind, but `error` would probably be useful too.

The chain; making it flag configured at this point seems pragmatic.

**Comment by juliusv** [comment]
@jevonearth Sorry, this time I dropped the ball. Have you had a chance to test https://github.com/ecadlabs/tezos_exporter/pull/15?

It pretty much does what's discussed here (single metric, chain ID as a flag). It doesn't include the error kind as a label, as that would only be applicable for the non-applied operations. If we wanted that, then we'd have to change to multiple metrics IMO. But probably including the error kind would be too much detail anyway.

**Comment by juliusv** [comment]
Awesome!
